import { NextResponse } from "next/server";
export async function GET() {
  return NextResponse.json(data);
}
const data = [
  "Manicure klasyczny",
  "Manicure hybrydowy",
  "Manicure żelowy",
  "Manicure akrylowy",
  "Manicure tytanowy",
  "Manicure japoński",
  "Manicure winylowy",
  "Manicure francuski",
  "Manicure ombre",
  "Manicure z efektem lustra",
  "Manicure z efektem kociego oka",
  "Manicure z efektem marmuru",
  "Manicure zdobienia artystyczne",
  "Manicure z kamieniami i cyrkoniami",
  "Manicure pielęgnacyjny",
  "Manicure męski",
  "Manicure na specjalne okazje (śluby, eventy)",
  "Manicure spa (z peelingiem i maską)",
  "Manicure regeneracyjny z odżywkami",
  "Manicure na formie",
  "Manicure z nadbudową płytki",
  "Manicure rekonstrukcja uszkodzonych paznokci",
  "Manicure z użyciem lakierów bio",
  "Manicure medyczny",
  "Manicure ekspresowy",
  "Manicure z bazą proteinową",
  "Manicure z efektem termo",
  "Pedicure klasyczny",
  "Pedicure hybrydowy",
  "Pedicure żelowy",
  "Pedicure spa (peeling, maska, masaż)",
  "Pedicure leczniczy",
  "Pedicure kosmetyczny",
  "Pedicure biologiczny (bez użycia narzędzi metalowych)",
  "Pedicure z użyciem frezarki",
  "Pedicure regeneracyjny",
  "Pedicure francuski",
  "Pedicure winylowy",
  "Pedicure męski",
  "Pedicure z usuwaniem modzeli i odcisków",
  "Pedicure z rekonstrukcją płytki paznokcia",
  "Pedicure na specjalne okazje",
  "Pedicure z aplikacją lakieru bio",
  "Pedicure z masażem stóp",
  "Pedicure z użyciem preparatów medycznych",
  "Pedicure z odżywką wzmacniającą",
  "Pedicure z parafiną na stopy",
  "Pedicure z efektami artystycznymi",
  "Pedicure z bazą proteinową",
  "Manicure wodny (z użyciem kąpieli wodnej)",
  "Manicure bezwodny (na sucho)",
  "Manicure parafinowy (z zastosowaniem ciepłej parafiny)",
  "Manicure mineralny",
  "Manicure z peelingiem chemicznym",
  "Manicure z zastosowaniem kwasów",
  "Manicure magnetyczny (z użyciem pyłków magnetycznych)",
  "Manicure z efektem syrenki",
  "Manicure z pyłkami holograficznymi",
  "Manicure z matowym wykończeniem",
  "Manicure z lakierami o przedłużonej trwałości",
  "Manicure dziecięcy (dla dzieci, z użyciem bezpiecznych lakierów)",
  "Manicure wegański (z wykorzystaniem ekologicznych produktów)",
  "Manicure z aplikacją folii transferowej",
  "Manicure z efektem perłowym",
  "Pedicure mineralny",
  "Pedicure z kąpielą solankową",
  "Pedicure z aromaterapią",
  "Pedicure z aplikacją maski algowej",
  "Pedicure z masażem refleksologicznym",
  "Pedicure z wykorzystaniem urządzeń podologicznych",
  "Pedicure z usuwaniem zrogowaceń frezarką",
  "Pedicure z terapią przeciwgrzybiczną",
  "Pedicure z kąpielą w soli morskiej",
  "Pedicure na bazie produktów wegańskich",
  "Pedicure z odświeżającym masażem stóp",
  "Pedicure z aplikacją biżuterii na paznokcie",
  "Pedicure z aplikacją specjalnych kompresów na pięty",
  "Manicure w stylu vintage (retro wzory i kolory)",
  "Manicure z efektem falujących linii",
  "Manicure holograficzny z efektem tęczy",
  "Manicure w stylu minimalistycznym (proste linie i kropki)",
  "Manicure z efektem lakieru magnetycznego (dynamiczne wzory pod wpływem magnesu)",
  "Manicure z użyciem specjalnych folii transferowych w różnych kolorach",
  "Manicure z aplikacją skórzanych elementów",
  "Manicure z użyciem muszli i naturalnych elementów",
  "Manicure w stylu graffiti (z wykorzystaniem sprayu do paznokci)",
  "Manicure w stylu 3D z aplikacjami (np. kwiaty, zwierzęta)",
  "Manicure z użyciem technik akwarelowych (wodna grafika)",
  "Manicure z techniką 'broken glass' (złamane szkło)",
  "Manicure w stylu cyberpunk (z neonowymi akcentami i efektem metalicznym)",
  "Manicure w stylu art déco (geometryczne wzory, złote akcenty)",
  "Manicure z użyciem nadruków na paznokciach (np. teksty, fotografie)",
  "Manicure z efektem szkła (transparentne, delikatne wykończenie)",
  "Manicure w stylu boho (naturalne kamienie, pióra, kwiaty)",
  "Manicure z techniką 'chameleon nails' (zmieniające kolor w zależności od kąta padania światła)",
  "Manicure w stylu punk (czarne akcenty, ćwieki, krzyżyki)",
  "Manicure z efektami cukierkowego połysku",
  "Manicure z zastosowaniem piasku (efekt piaskowych paznokci)",
  "Manicure z efektem szkliwionych paznokci (efekt wypolerowanej, lśniącej tafli)",
  "Manicure w stylu pop-art (żywe kolory, komiksowe wzory)",
  "Manicure ze wzorem zwierzęcym (np. leoparda, zebry)",
  "Manicure z użyciem złota i srebra (np. folie złote lub srebrne, brokat)",
  "Manicure z pyłkami fotoluminescencyjnymi (świecące w ciemności)",
  "Manicure z użyciem folii z efektem lustra (mirror nails)",
  "Manicure w stylu paisley (orientalne wzory na paznokciach)",
  "Manicure z efektem lustrzanej tafli",
  "Manicure z efektem galaktyki (wszystkie odcienie nieba i gwiazdy)",
  "Manicure z wykorzystaniem złotych liści (np. złote wtopione w żel)",
  "Manicure z malowaniem na paznokciach za pomocą techniki akrylowa (pędzle)",
  "Manicure z zastosowaniem lakiery w kamuflażu (camo nails)",
  "Manicure z efektami błyszczenia (efekt połyskującego brokatu)",
  "Manicure ze specjalnymi wzorami w kształcie serc, gwiazdek i innych symboli",
  "Manicure w stylu gotyckim (ciemne, mocne kolory, koronkowe wzory)",
  "Manicure z efektami wodnymi (technika z zanurzaniem paznokci w wodzie)",
  "Manicure z użyciem barwników spożywczych (do uzyskania intensywnych kolorów)",
  "Manicure w stylu pop-art z użyciem hologramów na paznokciach",
  "Manicure z zastosowaniem pudrów wulkanicznych (efekt chropowatości)",
  "Manicure z użyciem srebrnych, złotych i miedzianych proszków",
  "Manicure z ozdobnymi naszywkami na paznokciach",
  "Manicure z wykorzystaniem gotowych szablonów w kształcie figur geometrycznych",
  "Manicure z efektami przestrzennymi (np. zastosowanie folii 3D)",
  "Manicure z użyciem brokatu w kształcie gwiazdek, serc i innych elementów dekoracyjnych",
  "Manicure z nadrukami na paznokciach, inspirowanymi dziełami sztuki",
  "Manicure z efektem gradientu metalicznego",
  "Pedicure z efektem 'golden heels' (złote akcenty na piętach)",
  "Pedicure w stylu hipsterskim (minimalistyczne wzory, stonowane kolory)",
  "Pedicure z użyciem naturalnych kamieni szlachetnych",
  "Pedicure w stylu boho z koralikami i wstążkami",
  "Pedicure z kamieniami naturalnymi (np. turkus, ametyst)",
  "Pedicure z efektem skóry węża",
  "Pedicure z aplikacją soczewek optycznych na paznokciach (np. holograficzne elementy)",
  "Pedicure z efektem ombre w wersji ombré na stopach",
  "Pedicure z użyciem lśniących pereł i cyrkonii",
  "Pedicure w stylu etnicznym (np. z wzorami inspirowanymi kulturą afrykańską)",
  "Pedicure ze wzorami kwiatowymi (np. lawenda, róże)",
  "Pedicure z użyciem olejków eterycznych dla relaksu",
  "Pedicure ze złotymi akcentami i ozdobami",
  "Pedicure w stylu graffiti (artystyczne wzory na paznokciach)",
  "Pedicure z elementami metalicznymi i błyszczącymi detalami",
  "Pedicure z efektem aquarel (wodne plamy kolorów na paznokciach)",
  "Pedicure z efektami w kształcie gwiazdek i galaktyki",
  "Pedicure w stylu glamour (bogato zdobione paznokcie, z użyciem kamieni szlachetnych)",
  "Pedicure z zastosowaniem naturalnych ziół (np. rumianku, lawendy)",
  "Pedicure w stylu fluo (neonowe kolory na stopach)",
  "Pedicure z wykorzystaniem brokatu w płynie",
  "Pedicure z zastosowaniem kleju do paznokci dla uzyskania efektu lśniącej tafli",
];
